services:
  db:
    image: postgres:15
    container_name: neurova_db
    environment:
      POSTGRES_DB: neurova_clinical
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hareesh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
